# Generated by Django 3.1.7 on 2021-06-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUpsAsset',
            fields=[
                ('device_id', models.OneToOneField(db_column='Device_ID_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ups.loginuserdetail')),
                ('ups_rating', models.BigIntegerField(db_column='UPS_Rating')),
                ('voltage_range', models.CharField(db_column='Voltage_Range', max_length=50)),
                ('battery_rating', models.CharField(db_column='Battery_Rating', max_length=200)),
                ('number_of_batteries', models.BigIntegerField(db_column='Number_of_batteries')),
                ('operating_volts', models.BigIntegerField(db_column='Operating_Volts')),
                ('oem', models.CharField(db_column='OEM', max_length=50)),
                ('seller_name', models.CharField(db_column='Seller_Name', max_length=50)),
                ('service_provider', models.CharField(db_column='Service_Provider', max_length=50)),
                ('ups_make', models.CharField(db_column='UPS_Model_No', max_length=50)),
                ('ups_serial_no', models.CharField(db_column='UPS_Serial_No', max_length=100)),
                ('ups_warranty_start_date', models.DateField(db_column='UPS_Warranty_Start_Date')),
                ('ups_warranty_end_date', models.DateField(db_column='UPS_Warranty_End_Date')),
                ('ups_warranty_period', models.CharField(db_column='UPS_Warranty_Period', max_length=50)),
                ('ups_warranty_status', models.CharField(db_column='UPS_Warranty_Status', max_length=20)),
                ('battery_make', models.CharField(db_column='Battery_Make', max_length=50)),
                ('battery_model_no', models.CharField(db_column='Battery_Model_No', max_length=50)),
                ('battery_serial_no', models.CharField(db_column='Battery_Serial_No', max_length=100)),
                ('ups_date_of_installation', models.DateField(db_column='UPS_Date_Of_Installation')),
                ('battery_warranty_start_date', models.DateField(db_column='Battery_Warranty_Start_Date')),
                ('battery_warranty_end_date', models.DateField(db_column='Battery_Warranty_End_Date')),
                ('battery_warranty_period', models.CharField(db_column='Battery_Warranty_Period', max_length=50)),
                ('battery_warranty_status', models.CharField(db_column='Battery_Warranty_Status', max_length=20)),
                ('battery_replacement_date', models.DateField(db_column='Battery_Replacement_Date')),
            ],
            options={
                'db_table': 'login_ups_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginUpsServiceHistory',
            fields=[
                ('device_id', models.OneToOneField(db_column='Device_ID_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ups.loginuserdetail')),
                ('service_contract', models.CharField(db_column='Service_Contract', max_length=20)),
                ('service_provider', models.CharField(db_column='Service_Provider', max_length=100)),
                ('address', models.CharField(db_column='Address', max_length=100)),
                ('contact', models.CharField(db_column='Contact', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('battery_last_service_date', models.DateField(db_column='Battery_Last_Service_Date')),
                ('battery_next_service_date', models.DateField(db_column='Battery_Next_Service_Date')),
                ('last_service_date', models.DateField(db_column='Last_Service_Date')),
                ('activity', models.CharField(db_column='Activity', max_length=300)),
                ('remark', models.CharField(db_column='Remark', max_length=300)),
                ('activity1', models.CharField(db_column='Activity1', max_length=300)),
                ('remark1', models.CharField(db_column='Remark1', max_length=300)),
                ('next_service_date', models.DateField(db_column='Next_Service_Date')),
            ],
            options={
                'db_table': 'login_ups_service_history',
                'managed': False,
            },
        ),
    ]
