# Generated by Django 3.1.7 on 2021-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Customer_Photo',
            field=models.ImageField(default='media/pics/default.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Commissioning_Date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Date_Of_Installation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Warranty_End_Date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Warranty_Start_Date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
