# Generated by Django 3.1.7 on 2021-04-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210405_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCounterView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=20, null=True)),
                ('counter', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_counter',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DeviceCounter',
        ),
    ]
