# Generated by Django 3.1.7 on 2021-04-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210405_1318'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devicecounterview',
            table='device_counter_view',
        ),
    ]
