# Generated by Django 3.1.7 on 2021-04-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210405_1327'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fuelfilledreport',
            table='fuel_capacity_per_mm_based_check',
        ),
    ]
