# Generated by Django 3.1.7 on 2021-04-10 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210408_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgms_device_info',
            name='DGMS_Date_Of_Installation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
