# Generated by Django 3.1.7 on 2021-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210417_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Commissioning_Date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Date_Of_Installation',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Warranty_End_Date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Warranty_Start_Date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dgms_device_info',
            name='DGMS_Date_Of_Installation',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service_history',
            name='Next_Service_Date',
            field=models.DateField(max_length=50),
        ),
    ]
