# Generated by Django 3.1.7 on 2021-05-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210422_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMS_Service_History',
            fields=[
                ('Device_ID', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user_detail')),
                ('Service_Contract', models.CharField(choices=[('AMC', 'AMC'), ('ON-CALL', 'ON-CALL'), ('NONE', 'NONE')], default='AMC', max_length=20)),
                ('Service_Provider', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=20)),
                ('Last_Service_Date', models.DateField()),
                ('Activity', models.CharField(max_length=300)),
                ('Remark', models.CharField(max_length=300)),
                ('Activity1', models.CharField(default='NULL', max_length=300)),
                ('Remark1', models.CharField(default='NULL', max_length=300)),
                ('Next_Service_Date', models.DateField()),
                ('Customer_Name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EMS_Asset',
            fields=[
                ('Device_ID', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user_detail')),
                ('Rating_In_KVA', models.CharField(max_length=50)),
                ('Input_Voltage_Range', models.CharField(max_length=50)),
                ('S_No', models.CharField(max_length=50)),
                ('Cooling', models.CharField(choices=[('AIR COOLED', 'AIR COOLED'), ('OIL COOLED', 'OIL COOLED')], default='AIR COOLED', max_length=20)),
                ('Oil_Tank_Size', models.BigIntegerField()),
                ('Other_Info', models.CharField(max_length=100)),
                ('OEM', models.CharField(max_length=50)),
                ('Seller_Name', models.CharField(max_length=50)),
                ('Service_Provider', models.CharField(max_length=100)),
                ('Date_Of_Installation', models.DateField()),
                ('Warranty_Start_Date', models.DateField()),
                ('Warranty_End_Date', models.DateField()),
                ('Warranty_Period', models.CharField(max_length=50)),
                ('Warranty_Status', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=20)),
                ('EMS_Date_Of_Installation', models.DateField()),
                ('Other_Info_new', models.CharField(max_length=50)),
                ('Customer_Name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
        ),
    ]
