# Generated by Django 3.1.7 on 2021-05-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_ems_asset_ems_service_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ems_asset',
            name='Rating_In_KVA',
            field=models.BigIntegerField(),
        ),
    ]
