# Generated by Django 3.1.7 on 2021-06-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20210522_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='ems_service_history',
            name='Email',
            field=models.CharField(default='info@emot.co.in', max_length=50),
        ),
        migrations.AddField(
            model_name='service_history',
            name='Email',
            field=models.CharField(default='info@emot.co.in', max_length=50),
        ),
        migrations.CreateModel(
            name='UPS_Service_History',
            fields=[
                ('Device_ID', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user_detail')),
                ('Service_Contract', models.CharField(choices=[('AMC', 'AMC'), ('ON-CALL', 'ON-CALL'), ('NONE', 'NONE')], default='AMC', max_length=20)),
                ('Service_Provider', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=20)),
                ('Email', models.CharField(default='info@emot.co.in', max_length=50)),
                ('Battery_Last_Service_Date', models.DateField(max_length=50)),
                ('Battery_Next_Service_Date', models.DateField(max_length=50)),
                ('Last_Service_Date', models.DateField(max_length=50)),
                ('Activity', models.CharField(max_length=300)),
                ('Remark', models.CharField(max_length=300)),
                ('Activity1', models.CharField(default='NULL', max_length=300)),
                ('Remark1', models.CharField(default='NULL', max_length=300)),
                ('Next_Service_Date', models.DateField(max_length=50)),
                ('Customer_Name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
        ),
        migrations.CreateModel(
            name='UPS_Asset',
            fields=[
                ('Device_ID', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user_detail')),
                ('UPS_Rating', models.BigIntegerField()),
                ('Voltage_Range', models.CharField(max_length=50)),
                ('Battery_Rating', models.CharField(blank=True, max_length=200)),
                ('Number_of_batteries', models.BigIntegerField()),
                ('Operating_Volts', models.BigIntegerField()),
                ('OEM', models.CharField(max_length=50)),
                ('Seller_Name', models.CharField(max_length=50)),
                ('Service_Provider', models.CharField(max_length=50)),
                ('UPS_Make', models.CharField(max_length=50)),
                ('UPS_Model_No', models.CharField(max_length=50)),
                ('UPS_Serial_No', models.CharField(max_length=100)),
                ('UPS_Warranty_Start_Date', models.DateField(max_length=50)),
                ('UPS_Warranty_End_Date', models.DateField(max_length=50)),
                ('UPS_Warranty_Period', models.CharField(max_length=50)),
                ('UPS_Warranty_Status', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=20)),
                ('Battery_Make', models.CharField(max_length=50)),
                ('Battery_Model_No', models.CharField(max_length=50)),
                ('Battery_Serial_No', models.CharField(max_length=100)),
                ('UPS_Date_Of_Installation', models.DateField(max_length=50)),
                ('Battery_Warranty_Start_Date', models.DateField(max_length=50)),
                ('Battery_Warranty_End_Date', models.DateField(max_length=50)),
                ('Battery_Warranty_Period', models.CharField(max_length=50)),
                ('Battery_Warranty_Status', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=20)),
                ('Customer_Name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
        ),
    ]
