# Generated by Django 3.1.7 on 2021-06-04 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20210604_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='ups_asset',
            name='Battery_Replacement_Date',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 16, 28, 18, 908049), max_length=50),
        ),
    ]
