# Generated by Django 3.1.7 on 2021-06-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_ups_asset_battery_replacement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ups_asset',
            name='Battery_Replacement_Date',
            field=models.DateField(max_length=50),
        ),
    ]
