# Generated by Django 3.1.7 on 2021-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20210605_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ups_asset',
            name='Battery_Date_Of_Installation',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ups_asset',
            name='UPS_Type',
            field=models.CharField(max_length=70),
        ),
    ]
