# Generated by Django 3.1.7 on 2021-06-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20210605_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ups_asset',
            name='Battery_Rating',
            field=models.CharField(max_length=200),
        ),
    ]
