# Generated by Django 3.1.7 on 2021-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20210606_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ems_asset',
            name='Oil_Tank_Size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
