# Generated by Django 3.1.7 on 2021-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20210612_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ups_asset',
            name='Date_Of_Installation',
            field=models.DateField(),
        ),
    ]
