# Generated by Django 3.1.7 on 2021-06-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_automation_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='Device_ID',
            field=models.CharField(max_length=30),
        ),
    ]
