# Generated by Django 3.1.7 on 2021-07-01 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_auto_20210612_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Carpet_Area',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='Connected_Load',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='Sanction_Load',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='service_history',
            name='Battery_Last_Replacement_Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='service_history',
            name='Battery_Next_Replacement_Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='service_history',
            name='Next_Service_Date',
            field=models.DateField(),
        ),
    ]
