# Generated by Django 3.1.7 on 2021-07-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_auto_20210718_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Approvals', 'Approvals'), ('Warranty', 'Warranty'), ('Test certificate', 'Test certificate'), ('Service Reports', 'Service Reports'), ('Quotation', 'Quotation'), ('Other', 'Other')], default='Other', max_length=20)),
                ('File', models.FileField(blank=True, upload_to='')),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Device_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user_detail')),
            ],
        ),
    ]
