# Generated by Django 3.1.7 on 2021-07-18 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='Device_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
