# Generated by Django 3.1.7 on 2021-07-18 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_auto_20210718_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='Device_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user_detail'),
        ),
    ]
