# Generated by Django 3.1.7 on 2021-05-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEmsAsset',
            fields=[
                ('device_id', models.OneToOneField(db_column='Device_ID_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ems.loginuserdetail')),
                ('rating_in_kva', models.CharField(db_column='Rating_In_KVA', max_length=50)),
                ('input_voltage_range', models.CharField(db_column='Input_Voltage_Range', max_length=50)),
                ('s_no', models.CharField(db_column='S_No', max_length=50)),
                ('cooling', models.CharField(db_column='Cooling', max_length=20)),
                ('oil_tank_size', models.BigIntegerField(db_column='Oil_Tank_Size')),
                ('other_info', models.CharField(db_column='Other_Info', max_length=100)),
                ('oem', models.CharField(db_column='OEM', max_length=50)),
                ('seller_name', models.CharField(db_column='Seller_Name', max_length=50)),
                ('service_provider', models.CharField(db_column='Service_Provider', max_length=100)),
                ('date_of_installation', models.DateField(db_column='Date_Of_Installation')),
                ('warranty_start_date', models.DateField(db_column='Warranty_Start_Date')),
                ('warranty_end_date', models.DateField(db_column='Warranty_End_Date')),
                ('warranty_period', models.CharField(db_column='Warranty_Period', max_length=50)),
                ('warranty_status', models.CharField(db_column='Warranty_Status', max_length=20)),
                ('ems_date_of_installation', models.DateField(db_column='EMS_Date_Of_Installation')),
                ('other_info_new', models.CharField(db_column='Other_Info_new', max_length=50)),
            ],
            options={
                'db_table': 'login_ems_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginEmsServiceHistory',
            fields=[
                ('device_id', models.OneToOneField(db_column='Device_ID_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ems.loginuserdetail')),
                ('service_contract', models.CharField(db_column='Service_Contract', max_length=20)),
                ('service_provider', models.CharField(db_column='Service_Provider', max_length=100)),
                ('address', models.CharField(db_column='Address', max_length=100)),
                ('contact', models.CharField(db_column='Contact', max_length=20)),
                ('last_service_date', models.DateField(db_column='Last_Service_Date')),
                ('activity', models.CharField(db_column='Activity', max_length=300)),
                ('remark', models.CharField(db_column='Remark', max_length=300)),
                ('activity1', models.CharField(db_column='Activity1', max_length=300)),
                ('remark1', models.CharField(db_column='Remark1', max_length=300)),
                ('next_service_date', models.DateField(db_column='Next_Service_Date')),
            ],
            options={
                'db_table': 'login_ems_service_history',
                'managed': False,
            },
        ),
    ]
